apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: servicemesh-demo
  labels:
    app: app1
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
      version: v1
  template:
    metadata:
      labels:
        app: app1
        version: v1
    spec:
      containers:
      - name: app1
        image: app1:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_NAME
          value: "app1"
        - name: SERVICE_VERSION
          value: "v1"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: servicemesh-demo
  labels:
    app: app1
    service: app1
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: app1
