apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: servicemesh-demo
  labels:
    app: app2
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
      version: v1
  template:
    metadata:
      labels:
        app: app2
        version: v1
    spec:
      containers:
      - name: app2
        image: app2:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_NAME
          value: "app2"
        - name: SERVICE_VERSION
          value: "v1"
        - name: APP1_SERVICE
          value: "app1.servicemesh-demo.svc.cluster.local"
        - name: APP1_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: servicemesh-demo
  labels:
    app: app2
    service: app2
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: app2
